### ISSUE TITLE
хардкод в Content

### ISSUE THREAD

**Issue by cjbars** [Master8/Web_labs#4]
в методе getContent у вас есть проверка на допустимость переданного параметра. если у вас будут добавляться пункты меню, то вам придется переписывать и этот метод. Сделайте проверку наличия ключа в массиве items, тогда метод будет независимым от входных данных

**Comment by master8** [comment]
fixed https://github.com/Master8/Web_labs/commit/a4f03021232d98fa671a61cb4827bdea72b0ece3
