### ISSUE TITLE
в классе Menu избыточный массив

### ISSUE THREAD

**Issue by cjbars** [Master8/Web_labs#6]
в массиве items у вас хранятся избыточные данные
для генерации ссылки достаточно ключа массива. Попробуйте избавиться от избыточности

**Comment by master8** [comment]
не понял, нам же ещё нужно имя, не только ссылка

**Comment by cjbars** [comment]
Вот именно в ссылке у вас есть цифровое значение, имхо от него в данной реализации можно избавиться, и саму ссылку не хранить в массиве

**Comment by master8** [comment]
ааа, точно, понял)

**Comment by master8** [comment]
fixed https://github.com/Master8/Web_labs/commit/7fd880d3d0955644fde06424b3e619aef629ade8
